config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only:[:new, :create, :edit, :update] do
    resources :messages, only:[:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージがありません'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :members
  has_many :groups, through: :members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      flash[:alert] = '保存に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { @new_messages = @messages.where('id > ?', params[:id]) }
    end
  end

  def create
    @message = @group.messages.new(message_params)
      if @message.save
        respond_to do |format|
          format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
          format.json
        end
      else
        @messages = @group.messages.includes(:user)
        flash.now[:alert] = 'メッセージを入力してください'
        render :index
      end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def login_groups
    @groups = current_user.groups
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
       redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
       redirect_to edit_user_registration_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_posted_time(time)
    time_d = time + 9.hour
    time_d.strftime("%Y-%m-%d %H:%M ")
  end

end

app/views/chat/_chat.html.haml
.chat__header
  .left-header
    .left-header__title
      = @group.name
    %ul.left-header__members
      Members:
      - @group.users.each do |user|
        %li.member
          = user.name
  .right-header
    .right-header__button
      = link_to "Edit", new_group_path(@group)

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
    %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
    %ul
      - @group.errors.full_messages.each do |message|
        %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label グループ名
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat-group-user__name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "user_search_field"}チャットメンバーを追加
    .chat-group-form__field--right
      %input.chat-group-form__input#input-user-search{name: "keyword", type: "text", placeholder: '追加したいメンバーを入力してください'}
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_user"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix
          = f.hidden_field :user_ids, value: current_user.id, name: "group[user_ids][]"
          %p.chat-group-user__name
            = current_user.name
  .chat-group-form__field
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', group: @group

app/views/groups/index.html.haml
.wapper
  .side-bar
    = render "shared/side_bar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', group: @group

app/views/layouts/_notifications.html.haml
.notification
  .notice
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.message{ 'data-message-id': message.id }
  .upper_message
    .upper_message__user_name
      = message.user.name
    .upper_message__date
      = form_posted_time(message.created_at)
  .lower_message
    - if message.body.present?
      .lower_message__text
        = message.body
    = image_tag message.image, class: 'lower_message__text' if message.image.present?

app/views/messages/index.html.haml
.wapper
  .side-bar
    = render "shared/side_bar"
  .chat
    = render "chat/chat"
    .messages.js-messages
      = render partial: "message", collection: @messages
    .form
      = form_for [@group, @message] do |f|
        = f.text_field :body, class: 'form__message', placeholder: 'type a message'
        .form__mask
          = f.label :image, class: 'form__mask__image' do
            = fa_icon 'picture-o', class: 'icon'
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'form__submit'

app/views/shared/_side_bar.html.haml
.side-bar
  .header
    %h3.header_name
      = current_user.name
    %ul.header_lists
      %li.list
        = link_to new_group_path do
          = fa_icon "pencil-square-o"
      %li.list
        = link_to edit_user_registration_path(current_user) do
          = fa_icon "cog"
  .groups
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .group
          .group_name
            = group.name
          .group_message
            = group.show_last_message